//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTable.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самое полезное приложение для студентов, преподавателей и университетов.
        ///
        ///Актуальное расписание вуза автоматически обновляется в вашем кармане..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписание вузов.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to занятость аудитории.
        /// </summary>
        public static string AuditoriumBisyButton {
            get {
                return ResourceManager.GetString("AuditoriumBisyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аудитория.
        /// </summary>
        public static string Auditory {
            get {
                return ResourceManager.GetString("Auditory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аудитория {0}.
        /// </summary>
        public static string AuditoryNameTemplate {
            get {
                return ResourceManager.GetString("AuditoryNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписание вузов.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписание по умолчанию.
        /// </summary>
        public static string DefaultUniversityAndGroup {
            get {
                return ResourceManager.GetString("DefaultUniversityAndGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сообщить об ошибке.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to избранное.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@raspisaniye-vuzov.ru.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to группы.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписание группы.
        /// </summary>
        public static string GroupTimeTable {
            get {
                return ResourceManager.GetString("GroupTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to я - студент.
        /// </summary>
        public static string ImStudent {
            get {
                return ResourceManager.GetString("ImStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to я - преподаватель.
        /// </summary>
        public static string ImTeacher {
            get {
                return ResourceManager.GetString("ImTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лабороторные работы.
        /// </summary>
        public static string LaboratoryWork {
            get {
                return ResourceManager.GetString("LaboratoryWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лекции.
        /// </summary>
        public static string Lectures {
            get {
                return ResourceManager.GetString("Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мобильный сайт.
        /// </summary>
        public static string MobileSite {
            get {
                return ResourceManager.GetString("MobileSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет данных.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписания для этой недели у нас нет..
        /// </summary>
        public static string NoLessons {
            get {
                return ResourceManager.GetString("NoLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не нашли своего расписания?.
        /// </summary>
        public static string NoTimeTable {
            get {
                return ResourceManager.GetString("NoTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упс..
        /// </summary>
        public static string Ooops {
            get {
                return ResourceManager.GetString("Ooops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to практические занятия.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сообщить об ошибке.
        /// </summary>
        public static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы получили данные и потараемся всё исправить в ближайшее время..
        /// </summary>
        public static string ReportErrorOk {
            get {
                return ResourceManager.GetString("ReportErrorOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to факультеты.
        /// </summary>
        public static string SelectFaculty {
            get {
                return ResourceManager.GetString("SelectFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to университеты.
        /// </summary>
        public static string SelectUniversity {
            get {
                return ResourceManager.GetString("SelectUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отображать в расписании.
        /// </summary>
        public static string ShowInTheSchedule {
            get {
                return ResourceManager.GetString("ShowInTheSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to посмотреть на карте.
        /// </summary>
        public static string ShowMap {
            get {
                return ResourceManager.GetString("ShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так. Может быть проблемы с сетью, а может, что-то сломалось у нас..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расписание преподавателя.
        /// </summary>
        public static string TeachersTimeTable {
            get {
                return ResourceManager.GetString("TeachersTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в избранное.
        /// </summary>
        public static string ToFavorites {
            get {
                return ResourceManager.GetString("ToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из избранного.
        /// </summary>
        public static string Unfavorite {
            get {
                return ResourceManager.GetString("Unfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to версия:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} неделя.
        /// </summary>
        public static string WeekNumber {
            get {
                return ResourceManager.GetString("WeekNumber", resourceCulture);
            }
        }
    }
}
